import type { Metadata } from "next";
import localFont from "next/font/local";
import SdieNav from "@/app/componets/SideNav/SdieNav";
import Providers from "./Providers";
import "./globals.css";
import MobileNav from "./componets/SideNav/MobileNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex gap-0 md:gap-5 pr-5 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <section className="h-screen p-3">
            <SdieNav />
          </section>
          <main className="w-full">
            <MobileNav />
            <div className="h-screen overflow-y-scroll py-10">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
